
window.padding.x = 12
window.padding.y = 12
# Colors (Alabaster Dark)
# author tonsky

window.opacity = 0.8

[colors.primary]  
background = '#0F0F0F'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[cursor]
style = 'beam'
unfocused_hollow = false



[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#55FF55'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#55FF55'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'

[font.normal]
family = 'JetBrains Mono Nerd Font'

[general]
import = [
    "~/.config/alacritty/themes/themes/{theme}.toml"
]
